export const avatarOptions = [
  { filename: "/avatars/BettyCougar.png", name: "Betty Cougar" },
  { filename: "/avatars/ChasinMoreCheese.png", name: "Chasin' More Cheese" },
  { filename: "/avatars/Finhead.png", name: "Finhead" },
  { filename: "/avatars/PigSaw.png", name: "Pigsaw" },
  { filename: "/avatars/PsychoFryers.png", name: "Psycho Fryers" },
  { filename: "/avatars/ToastFace.png", name: "Toast Face" },
  { filename: "/avatars/ChunkyLeeRay.png", name: "Chunky Lee Ray" },
  { filename: "/avatars/SmartTheClown.png", name: "Smart the Clown" },
  { filename: "/avatars/Grannywise.png", name: "Grannywise" },
  { filename: "/avatars/Handy_Man.png", name: "Handy Man" },
  { filename: "/avatars/Shredderface.png", name: "Shredderface" },
  { filename: "/avatars/Regazuzu.png", name: "Regazuzu" },
  { filename: "/avatars/GroovyMcBoomstick.png", name: "Groovy McBoomstick" },
  { filename: "/avatars/XenoMorphinTime.png", name: "Xeno Morphin Time" },
  { filename: "/avatars/Predatourist.png", name: "Predatourist" },
];
